name: Python package

on:
  push:
    branches:
      - '*'

jobs:
  build-310:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        orjson: [true, false]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Uninstall orjson if necessary
        run: |
          if [ "${{ matrix.orjson }}" == "false" ]; then
            pip uninstall -y orjson
          fi

      - name: Run tests with Python 3.10
        run: pytest test
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  build-311:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        orjson: [true, false]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Uninstall orjson if necessary
        run: |
          if [ "${{ matrix.orjson }}" == "false" ]; then
            pip uninstall -y orjson
          fi

      - name: Run tests with Python 3.11
        run: pytest test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
  

